export const countries = [
  { id: 1, name: "|EU| FRANCE HEVC" },
  { id: 2, name: "|EU| FRANCE GENERAL" },
  { id: 3, name: "|EU| FRANCE SPORTS" },
  { id: 4, name: "|EU| FRANCE NEWS" },
  { id: 5, name: "|EU| FRANCE CINEMA" },
  { id: 6, name: "|EU| FRANCE DOCUMENTAIRE" },
  { id: 7, name: "|EU| FRANCE ENTERTAINMENT" },
  { id: 8, name: "|EU| FRANCE KIDS" },
  { id: 9, name: "|EU| / FRENCH" },
  { id: 10, name: "|CAR| FRENCH" },
  { id: 11, name: "|EU| FRANCE K" },
  { id: 12, name: "|EU| SWISS HD" },
  { id: 13, name: "|UK| GENERAL" },
  { id: 14, name: "|UK| NEWS" },
  { id: 15, name: "|UK| ENTERTAINMENT" },
  { id: 16, name: "|UK| SPORTS" },
  { id: 17, name: "|UK| EPL SOCCER" },
  { id: 18, name: "|UK| EFL SOCCER" },
  { id: 19, name: "|UK| NATIONAL LEAGUE" },
  { id: 20, name: "UK| AMAZON PRIME" },
  { id: 21, name: "|UK| VIAPLAY PPV" },
  { id: 22, name: "|UK| MOVIES" },
  { id: 23, name: "|UK| KIDS" },
  { id: 24, name: "|UK| DOCUMENTARY" },
  { id: 25, name: "|UK| DISCOVERY+" },
  { id: 26, name: "|UK| / FLEX" },
  { id: 27, name: "|UK| MUSIC" },
  { id: 28, name: "|UK| PPV EVENTS" },
  { id: 29, name: "|UK| WORLD SPORTS" },
  { id: 30, name: "|UK| SCOTTISH FOOTBALL" },
  { id: 31, name: "|UK| OTHER SPORTS" },
  { id: 32, name: "|IE| IRELAND" },
  { id: 33, name: "|NA| / ENGLISH K" },
  { id: 34, name: "|AR| STARZPLAY / AD SPORTS" },
  { id: 35, name: "|AR| BEIN SPORTS" },
  { id: 36, name: "|AR| BEIN SPORTS K" },
  { id: 37, name: "|AR| SSC SPORTS" },
  { id: 38, name: "|AR| BEIN ENTERTAINMENT" },
  { id: 39, name: "|AR| BEIN PREMIUM PLAY" },
  { id: 40, name: "|AR| ARABIC NEWS & FACTUAL" },
  { id: 41, name: "|AR| MOROCCO" },
  { id: 42, name: "|AR| ALGERIA" },
  { id: 43, name: "|AR| TUNISA" },
  { id: 44, name: "|AR| ISLAMIC" },
  { id: 45, name: "|AR| ARABIC KIDS" },
  { id: 46, name: "|AR| ROTANA | ART" },
  { id: 47, name: "|AR| MBC" },
  { id: 48, name: "|AR| OSN" },
  { id: 49, name: "|AR| AL FAJER" },
  { id: 50, name: "|AR| EGYPT" },
  { id: 51, name: "|AR| LEBANON" },
  { id: 52, name: "|AR| UAE" },
  { id: 53, name: "|AR| ABU DHABI SPORTS" },
  { id: 54, name: "|AR| MAURITANIA" },
  { id: 55, name: "|AR| LIBYA" },
  { id: 56, name: "|AR| BAHRAIN" },
  { id: 57, name: "|AR| JORDAN" },
  { id: 58, name: "|AR| YEMEN" },
  { id: 59, name: "|AR| SAOUDI" },
  { id: 60, name: "|AR| SYRIA" },
  { id: 61, name: "|AR| IRAQ" },
  { id: 62, name: "|AR| SUDAN" },
  { id: 63, name: "|AR| CHRISTIAN" },
  { id: 64, name: "|AR| PALESTINE" },
  { id: 65, name: "|AR| QATAR" },
  { id: 66, name: "|AR| KUWAIT" },
  { id: 67, name: "|AR| ARABIC VIP" },
  { id: 68, name: "|AR| SPORT" },
  { id: 69, name: "|AR| NETFLIX" },
  { id: 70, name: "|AR| SHAHID. CINEMA" },
  { id: 71, name: "|AR| GOBX GROUP" },
  { id: 72, name: "|AR| SHAHID. VIP" },
  { id: 73, name: "|AR| DRAMA PLAY" },
  { id: 74, name: "|AR| COMEDY PLAY" },
  { id: 75, name: "|AR| WATCH IT" },
  { id: 76, name: "|AR| STARZ PLAY" },
  { id: 77, name: "|AR| AMAZON PRIME" },
  { id: 78, name: "|AR| HBO" },
  { id: 79, name: "|AR| PREMIUM PLAY" },
  { id: 80, name: "|AR| MUSIC" },
  { id: 81, name: "|AR| CHEF OMAR" },
  { id: 82, name: "|ES| REPETICIÓN DE FÚTBOL" },
  { id: 83, name: "|ES| ESPAÑA HEVC" },
  { id: 84, name: "|ES| DEPORTES" },
  { id: 85, name: "|ES| GENERAL" },
  { id: 86, name: "|ES| CINEMA" },
  { id: 87, name: "|ES| NIÑOS" },
  { id: 88, name: "|ES| DOCUMENTALES" },
  { id: 89, name: "|ES| LOCALS" },
  { id: 90, name: "|ES| M.PELICULAS" },
  { id: 91, name: "|EU| / SPANISH" },
  { id: 92, name: "|DE| ALLGEMEINES" },
  { id: 93, name: "|DE| SPORT" },
  { id: 94, name: "|DE| DAZN PRIME" },
  { id: 95, name: "|DE| SKY FILM UND SERIE" },
  { id: 96, name: "|DE| KINDER" },
  { id: 97, name: "|DE| UNTERHALTUNG" },
  { id: 98, name: "|DE| REGIONAL" },
  { id: 99, name: "|DE| K+ PAKET" },
  { id: 100, name: "|DE| NATUR" },
  { id: 101, name: "|EU| / GERMANY" },
  { id: 102, name: "|PT| EMGERAL" },
  { id: 103, name: "|PT| DESPORTO" },
  { id: 104, name: "|PT| FILMES E SÉRIES" },
  { id: 105, name: "|PT| DOCUMENTARIOS" },
  { id: 106, name: "|PT| CRIANÇAS" },
  { id: 107, name: "|PT| INTERNACIONAL" },
  { id: 108, name: "|IT| GENERALE" },
  { id: 109, name: "|IT| CINEMA" },
  { id: 110, name: "|IT| SPORT" },
  { id: 111, name: "|IT| BAMBINI" },
  { id: 112, name: "|IT| DOCUMENTARIO" },
  { id: 113, name: "|EU| BELGIQUE HD" },
  { id: 114, name: "|EU| BELGIUM VL" },
  { id: 115, name: "|EU| BELGIUM WL" },
  { id: 116, name: "|NL| ALGEMEEN" },
  { id: 117, name: "|NL| SPORT" },
  { id: 118, name: "|NL| VIAPLAY SPORT" },
  { id: 119, name: "|NL| KINDEREN" },
  { id: 120, name: "|NL| ENTERTAINMENT" },
  { id: 121, name: "|NL| MUZIEK" },
  { id: 122, name: "|NL| NATUUR" },
  { id: 123, name: "|NL| REGIONAAL" },
  { id: 124, name: "|NL| BUITENLAND" },
  { id: 125, name: "|EU| NEDERLAND K ULTRA" },
  { id: 126, name: "|PL| POLAND FHD" },
  { id: 127, name: "|PL| INFORMACJE" },
  { id: 128, name: "|PL| FILMOWE" },
  { id: 129, name: "|PL| KULTURA" },
  { id: 130, name: "|PL| OGÓLNE" },
  { id: 131, name: "|PL| MUZYKA | DZIECI" },
  { id: 132, name: "|PL| SPORTOWE" },
  { id: 133, name: "|PL| NA HD" },
  { id: 134, name: "|PL| VIAPLAY SPORT" },
  { id: 135, name: "|AS| TURKEY | ULUSAL" },
  { id: 136, name: "|AS| TURKEY | DIGER" },
  { id: 137, name: "|AS| TURKEY | COCUK" },
  { id: 138, name: "|AS| TURKEY | SINEMA" },
  { id: 139, name: "|AS| TURKEY | SPOR" },
  { id: 140, name: "|AS| KURDISTAN" },
  { id: 141, name: "|EU| ISRAEL" },
  { id: 142, name: "|EU| CZECH" },
  { id: 143, name: "|ALB| GENERAL" },
  { id: 144, name: "|ALB| NEWS" },
  { id: 145, name: "|ALB| MOVIES" },
  { id: 146, name: "|ALB| DOCUMENTARY" },
  { id: 147, name: "|ALB| CHILDREN" },
  { id: 148, name: "|ALB| SPORTS" },
  { id: 149, name: "|ALB| MUSIC" },
  { id: 150, name: "|ALB| ISLAMIC" },
  { id: 151, name: "|ALB| KOSOVO" },
  { id: 152, name: "|EU| ROMANIA" },
  { id: 153, name: "|GR| ΕΛΛΑΔΑ" },
  { id: 154, name: "|GR| ΚΥΠΡΟΣ" },
  { id: 155, name: "|GR| ΣINEMA" },
  { id: 156, name: "|GR| ΑΘΛHTIKA" },
  { id: 157, name: "|GR| ΠAIΔIKA" },
  { id: 158, name: "|EU| RUSSIA" },
  { id: 159, name: "|EU| LITHUANIA" },
  { id: 160, name: "|BLN| SPORTS" },
  { id: 161, name: "|BLN| SERBIA" },
  { id: 162, name: "|BLN| CROATIA" },
  { id: 163, name: "|BLN| BOSNIA" },
  { id: 164, name: "|BLN| SLOVENIA" },
  { id: 165, name: "|BLN| MACEDONIA" },
  { id: 166, name: "|BLN| MONTENEGRO" },
  { id: 167, name: "|EU| BULGARIA" },
  { id: 168, name: "|EU| HUNGARIA" },
  { id: 169, name: "|EU| UKRAINE" },
  { id: 170, name: "|AM| BRAZIL" },
  { id: 171, name: "|SA| LATINO" },
  { id: 172, name: "|AM| ARGENTINA" },
  { id: 173, name: "|AM| BOLIVIA" },
  { id: 174, name: "|AM| CHILE" },
  { id: 175, name: "|AM| PANAMA" },
  { id: 176, name: "|AM| COLOMBIA" },
  { id: 177, name: "|AM| HONDURAS" },
  { id: 178, name: "|AM| DOMINICANA REP" },
  { id: 179, name: "|AM| ECUADOR" },
  { id: 180, name: "|AM| EL SALVADOR" },
  { id: 181, name: "|AM| MEXICO" },
  { id: 182, name: "|AM| PARAGUAY" },
  { id: 183, name: "|AM| PERU" },
  { id: 184, name: "|AM| URUGUAY" },
  { id: 185, name: "|AM| COSTA RICA" },
  { id: 186, name: "|AM| NICARAGUA" },
  { id: 187, name: "|NA| USA GENERAL" },
  { id: 188, name: "|NA| USA NEWS" },
  { id: 189, name: "|NA| USA KIDS" },
  { id: 190, name: "|NA| USA MOVIES" },
  { id: 191, name: "|NA| USA SPORTS" },
  { id: 192, name: "|NA| USA ABC" },
  { id: 193, name: "|NA| USA CBS" },
  { id: 194, name: "|NA| USA FOX" },
  { id: 195, name: "|NA| USA NBC" },
  { id: 196, name: "|NA| USA PBS" },
  { id: 197, name: "|NA| USA CW & MY" },
  { id: 198, name: "|NA| USA NBA" },
  { id: 199, name: "|NA| USA NFL" },
  { id: 200, name: "|NA| USA NHL" },
  { id: 201, name: "|NA| USA NBCS" },
  { id: 202, name: "|NA| USA MLB" },
  { id: 203, name: "|NA| USA MILB" },
  { id: 204, name: "|NA| USA NCAA" },
  { id: 205, name: "|NA| USA ESPN+" },
  { id: 206, name: "|NA| USA MLS" },
  { id: 207, name: "|NA| USA FLO" },
  { id: 208, name: "|NA| TUDN SPORTS" },
  { id: 209, name: "|NA| PPV LIVE EVENT" },
  { id: 210, name: "|NA| TELEMUNDO" },
  { id: 211, name: "|NA| UNIVISION" },
  { id: 212, name: "|NA| UNIMAS" },
  { id: 213, name: "|NA| / ENGLISH" },
  { id: 214, name: "|AM| CANADA" },
  { id: 215, name: "|NA| CANADA FR" },
  { id: 216, name: "|NA| HOCKEY LEAGUE" },
  { id: 217, name: "|AS| IRAN" },
  { id: 218, name: "|AS| NEPAL" },
  { id: 219, name: "|AS| CRICKET" },
  { id: 220, name: "|AS| INDIA - EU" },
  { id: 221, name: "|AS| INDIA" },
  { id: 222, name: "|AS| PAKISTAN" },
  { id: 223, name: "|AS| TAMIL" },
  { id: 224, name: "|AS| SPORTS" },
  { id: 225, name: "WORLD CRICKET" },
  { id: 226, name: "|AS| ENGLISH" },
  { id: 227, name: "|AS| BANGLA" },
  { id: 228, name: "|AS| PUNJABI" },
  { id: 229, name: "|AS| GUJARATI" },
  { id: 230, name: "|AS| MALAYALAM" },
  { id: 231, name: "|AS| MARATHI" },
  { id: 232, name: "|AS| TELUGU" },
  { id: 233, name: "|AS| KANNADA" },
  { id: 234, name: "|AS| BHOJPURI" },
  { id: 235, name: "|AS| ASSAM" },
  { id: 236, name: "|AS| SRILANKA" },
  { id: 237, name: "|AF| C+ AFRIQUE" },
  { id: 238, name: "|AF| DSTV AFRIQUE" },
  { id: 239, name: "|AF| SOMALIA" },
  { id: 240, name: "|AF| SENEGAL" },
  { id: 241, name: "|AF| CONGO/GABON" },
  { id: 242, name: "|AF| MALI" },
  { id: 243, name: "|AF| CAMEROON" },
  { id: 244, name: "|AF| GHANA" },
  { id: 245, name: "|AF| NIGERIA" },
  { id: 246, name: "|AF| AFRIQUE OTHERS" },
  { id: 247, name: "|AU| AUSTRALIA" },
  { id: 248, name: "|EU| SWEDEN HD" },
  { id: 249, name: "|AS| AFGHANISTAN" },
  { id: 250, name: "|AS| ARMENIA" },
  { id: 251, name: "|EU| GEORGIE" },
  { id: 252, name: "|EU| DENMARK HD" },
  { id: 253, name: "|EU| NORWAY HD" },
  { id: 254, name: "|EU| FINLAND HD" },
  { id: 255, name: "|AS| VIETNAM" },
  { id: 256, name: "|AS| HONGKONG" },
  { id: 257, name: "|AS| PHILIPPINES" },
  { id: 258, name: "|AS| SOUTH KOREA" },
  { id: 259, name: "|SA| CARRIBEAN" },
  { id: 260, name: "|EU| AUSTRIA HD" },
  { id: 261, name: "|EU| AUSTRIA PLUTO TV" },
  { id: 262, name: "|NZ| NEW ZEALAND" },
  { id: 263, name: "|SA| SURINAME" },
  { id: 264, name: "|TH| THAILANDE" },
  { id: 265, name: "|AZ| AZERBAYCAN" },
  { id: 266, name: "|MT| MALTA" },
  { id: 267, name: "|AS| INDONESIA" },
  { id: 268, name: "|EU| CYPRUS" },
  { id: 269, name: "JAPAN" },
  { id: 270, name: "|AS| MALAYSIA" },
];
